"""Tests for rules/pg_conf.py: HBA trust/md5/error,
ALTER SYSTEM drift.
"""

from __future__ import annotations

from radar_analyst.parse.pg_conf import HbaRule
from radar_analyst.rules.pg_conf import (
    alter_system_drift,
    hba_config_error,
    md5_method_present,
    trust_method_present,
)


def _rule(
    type: str = "host",
    auth_method: str = "scram-sha-256",
    address: str = "0.0.0.0",
    rule_number: int = 1,
    error: str = "",
) -> HbaRule:
    return HbaRule(
        rule_number=rule_number,
        type=type,
        database="{all}",
        user_name="{all}",
        address=address,
        auth_method=auth_method,
        options="",
        error=error,
    )


# ---------------------------------------------------------------
# trust_method_present
# ---------------------------------------------------------------

def test_trust_fires_on_host_trust() -> None:
    parsed = {
        "pg.hba_file_rules": [_rule(type="host", auth_method="trust")]
    }
    out = trust_method_present(parsed)
    assert len(out) == 1
    assert out[0].severity == "critical"
    assert out[0].rule_id == "pg.conf.hba_trust"


def test_trust_fires_on_hostssl_trust() -> None:
    parsed = {
        "pg.hba_file_rules": [
            _rule(type="hostssl", auth_method="trust")
        ]
    }
    out = trust_method_present(parsed)
    assert len(out) == 1


def test_trust_silent_on_local_trust() -> None:
    # Unix-socket trust for postgres is common and acceptable.
    parsed = {
        "pg.hba_file_rules": [_rule(type="local", auth_method="trust")]
    }
    assert trust_method_present(parsed) == []


def test_trust_silent_on_host_scram() -> None:
    parsed = {
        "pg.hba_file_rules": [
            _rule(type="host", auth_method="scram-sha-256")
        ]
    }
    assert trust_method_present(parsed) == []


def test_trust_silent_when_no_data() -> None:
    assert trust_method_present({}) == []


def test_trust_silent_on_empty_list() -> None:
    assert trust_method_present({"pg.hba_file_rules": []}) == []


# ---------------------------------------------------------------
# md5_method_present
# ---------------------------------------------------------------

def test_md5_fires_on_host_md5() -> None:
    parsed = {
        "pg.hba_file_rules": [_rule(type="host", auth_method="md5")]
    }
    out = md5_method_present(parsed)
    assert len(out) == 1
    assert out[0].severity == "warning"
    assert out[0].rule_id == "pg.conf.hba_md5"


def test_md5_fires_on_local_md5() -> None:
    parsed = {
        "pg.hba_file_rules": [_rule(type="local", auth_method="md5")]
    }
    out = md5_method_present(parsed)
    assert len(out) == 1


def test_md5_silent_on_scram() -> None:
    parsed = {
        "pg.hba_file_rules": [
            _rule(type="host", auth_method="scram-sha-256")
        ]
    }
    assert md5_method_present(parsed) == []


def test_md5_silent_when_no_data() -> None:
    assert md5_method_present({}) == []


# ---------------------------------------------------------------
# hba_config_error
# ---------------------------------------------------------------

def test_hba_error_fires_on_error_column() -> None:
    parsed = {
        "pg.hba_file_rules": [_rule(error="syntax error near 'host'")]
    }
    out = hba_config_error(parsed)
    assert len(out) == 1
    assert out[0].severity == "warning"
    assert out[0].rule_id == "pg.conf.hba_error"


def test_hba_error_silent_on_clean_rules() -> None:
    parsed = {
        "pg.hba_file_rules": [_rule(error=""), _rule(error="")]
    }
    assert hba_config_error(parsed) == []


def test_hba_error_silent_when_no_data() -> None:
    assert hba_config_error({}) == []


# ---------------------------------------------------------------
# alter_system_drift
# ---------------------------------------------------------------

_AUTO_CONF_HEADER_ONLY = (
    "# Do not edit this file manually!\n"
    "# It will be overwritten by the ALTER SYSTEM command.\n"
)

_AUTO_CONF_WITH_SETTINGS = (
    "# Do not edit this file manually!\n"
    "# It will be overwritten by the ALTER SYSTEM command.\n"
    "work_mem = '64MB'\n"
    "max_connections = '200'\n"
)


def test_alter_system_fires_when_settings_present() -> None:
    parsed = {
        "pg.conf.postgresql_auto": _AUTO_CONF_WITH_SETTINGS
    }
    out = alter_system_drift(parsed)
    assert len(out) == 1
    assert out[0].severity == "warning"
    assert out[0].rule_id == "pg.conf.alter_system_drift"


def test_alter_system_silent_on_header_only() -> None:
    parsed = {"pg.conf.postgresql_auto": _AUTO_CONF_HEADER_ONLY}
    assert alter_system_drift(parsed) == []


def test_alter_system_silent_when_no_data() -> None:
    assert alter_system_drift({}) == []


def test_alter_system_silent_on_empty_string() -> None:
    parsed = {"pg.conf.postgresql_auto": ""}
    assert alter_system_drift(parsed) == []
