-- The initial schema, in one file.
--
-- Pre-release software does not accumulate migrations: while there
-- is nothing deployed to upgrade, a change belongs in this file
-- rather than in a new one beside it. The runner and its bookkeeping
-- stay, ready for the first migration that has to preserve data.

CREATE TABLE IF NOT EXISTS radar.uploads (
    id UUID PRIMARY KEY,
    filename TEXT NOT NULL,
    storage_url TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    hostname TEXT,
    archive_timestamp TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    archive_files JSONB
);

CREATE TABLE IF NOT EXISTS radar.jobs (
    id UUID PRIMARY KEY,
    upload_id UUID NOT NULL
        REFERENCES radar.uploads(id) ON DELETE CASCADE,
    state TEXT NOT NULL,
    phase TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error TEXT,
    ai_provider TEXT
);

CREATE TABLE IF NOT EXISTS radar.snapshots (
    upload_id UUID PRIMARY KEY
        REFERENCES radar.uploads(id) ON DELETE CASCADE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS radar.findings (
    id UUID PRIMARY KEY,
    upload_id UUID NOT NULL
        REFERENCES radar.uploads(id) ON DELETE CASCADE,
    rule_id TEXT NOT NULL,
    category TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT
);
CREATE INDEX IF NOT EXISTS findings_upload_category
    ON radar.findings (upload_id, category);

CREATE TABLE IF NOT EXISTS radar.briefs (
    id UUID PRIMARY KEY,
    upload_id UUID NOT NULL
        REFERENCES radar.uploads(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    verdict TEXT,
    markdown TEXT NOT NULL,
    prompt_tokens INT,
    completion_tokens INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS briefs_upload_category
    ON radar.briefs (upload_id, category);

-- Documentation lives in the database, so anyone reading the state
-- with psql learns what a column means without a document beside it.

COMMENT ON SCHEMA radar IS
    'State for pgEdge Radar Analyst: uploaded radar archives and '
    'the assessments derived from them. Never holds anything about '
    'the PostgreSQL server an archive was collected from.';

-- uploads -----------------------------------------------------------
COMMENT ON TABLE radar.uploads IS
    'One uploaded radar archive. The bytes live in the blob store; '
    'this row holds where they are and what the archive says about '
    'itself.';
COMMENT ON COLUMN radar.uploads.id IS
    'Upload identifier, generated by the service and used in every '
    'API path for this archive.';
COMMENT ON COLUMN radar.uploads.filename IS
    'Name the archive was uploaded under, as given by the client.';
COMMENT ON COLUMN radar.uploads.storage_url IS
    'Opaque blob-store address, for example file:// for the local '
    'filesystem store. The schema does not depend on the scheme.';
COMMENT ON COLUMN radar.uploads.size_bytes IS
    'Size of the stored archive in bytes, counted while streaming '
    'it in.';
COMMENT ON COLUMN radar.uploads.sha256 IS
    'Hex sha256 of the stored archive, computed in the same '
    'streaming pass as size_bytes.';
COMMENT ON COLUMN radar.uploads.hostname IS
    'Host the archive was collected from: read from the archive name '
    'at upload, then from the archive itself once it has been read. '
    'Null when neither says.';
COMMENT ON COLUMN radar.uploads.archive_timestamp IS
    'When radar collected the archive, as the archive name records '
    'it: the local clock time of the host, which the name gives '
    'without a zone, stored as UTC. Null when the name is not in '
    'radar form.';
COMMENT ON COLUMN radar.uploads.created_at IS
    'When the upload was accepted by the service.';
COMMENT ON COLUMN radar.uploads.archive_files IS
    'Inventory of every entry in the archive, as a JSON array of '
    '{path, kind, dbname, size}. Entries no parser claims are '
    'stored with kind = null, which is how a new radar collector '
    'shows up rather than disappearing silently.';

-- jobs --------------------------------------------------------------
COMMENT ON TABLE radar.jobs IS
    'One assessment run over one upload. Deleted with its upload.';
COMMENT ON COLUMN radar.jobs.id IS
    'Job identifier, used in the job and progress-stream paths.';
COMMENT ON COLUMN radar.jobs.upload_id IS
    'Archive this job assessed.';
COMMENT ON COLUMN radar.jobs.state IS
    'queued, parsing, analyzing, done, or failed.';
COMMENT ON COLUMN radar.jobs.phase IS
    'Most recent pipeline stage, for the progress stream: complete '
    'after a successful run, the last stage after a failure. Null '
    'before the first stage and for a job that a restart marked '
    'failed.';
COMMENT ON COLUMN radar.jobs.started_at IS
    'When the job began, or null while it is still queued.';
COMMENT ON COLUMN radar.jobs.finished_at IS
    'When the job reached done or failed, or null while running.';
COMMENT ON COLUMN radar.jobs.error IS
    'Why the job failed. Null on success.';
COMMENT ON COLUMN radar.jobs.ai_provider IS
    'Provider that was configured for this run, recorded so a '
    'brief can be read in the light of what wrote it.';

-- snapshots ---------------------------------------------------------
COMMENT ON TABLE radar.snapshots IS
    'Parsed host and PostgreSQL context for one upload, plus the '
    'coverage canary listing archive paths no parser claimed.';
COMMENT ON COLUMN radar.snapshots.upload_id IS
    'Archive this snapshot was parsed from.';
COMMENT ON COLUMN radar.snapshots.data IS
    'The snapshot itself: host facts, PostgreSQL settings, '
    'per-database summaries, and unknown_entries.';

-- findings ----------------------------------------------------------
COMMENT ON TABLE radar.findings IS
    'Deterministic results. Every row was produced by a rule in '
    'rules/, never by a language model, so the same archive always '
    'yields the same findings.';
COMMENT ON COLUMN radar.findings.id IS
    'Finding identifier.';
COMMENT ON COLUMN radar.findings.upload_id IS
    'Archive this finding was derived from.';
COMMENT ON COLUMN radar.findings.rule_id IS
    'Rule that fired, matching the name in rules/.';
COMMENT ON COLUMN radar.findings.category IS
    'Diagnostic category this finding is reported under.';
COMMENT ON COLUMN radar.findings.severity IS
    'How bad it is. Sets the floor for the category verdict, which '
    'is why a verdict survives a provider outage.';
COMMENT ON COLUMN radar.findings.title IS
    'One-line statement of what was found.';
COMMENT ON COLUMN radar.findings.detail IS
    'Longer explanation, including what to do about it.';

-- briefs ------------------------------------------------------------
COMMENT ON TABLE radar.briefs IS
    'Per-category narrative written by the configured provider. '
    'The only part of an assessment that can be missing: findings '
    'and verdicts do not depend on a provider answering.';
COMMENT ON COLUMN radar.briefs.id IS
    'Brief identifier.';
COMMENT ON COLUMN radar.briefs.upload_id IS
    'Archive this brief describes.';
COMMENT ON COLUMN radar.briefs.category IS
    'Diagnostic category, or a per-database key for a '
    'database-level brief.';
COMMENT ON COLUMN radar.briefs.provider IS
    'Provider that produced this brief.';
COMMENT ON COLUMN radar.briefs.model IS
    'Model that produced this brief.';
COMMENT ON COLUMN radar.briefs.verdict IS
    'HEALTHY, WARNING, or CRITICAL, never below the floor set by '
    'this category''s worst finding. UNKNOWN means the archive '
    'carried no data for the category.';
COMMENT ON COLUMN radar.briefs.markdown IS
    'The brief itself. Carries a short "unavailable" note when the '
    'provider could not be reached.';
COMMENT ON COLUMN radar.briefs.prompt_tokens IS
    'Prompt tokens billed for this brief, when the provider '
    'reports them.';
COMMENT ON COLUMN radar.briefs.completion_tokens IS
    'Completion tokens billed for this brief, when the provider '
    'reports them.';
COMMENT ON COLUMN radar.briefs.created_at IS
    'When the brief was written.';

-- schema_migrations -------------------------------------------------
COMMENT ON TABLE radar.schema_migrations IS
    'Which migration files have been applied. Written by the '
    'service at startup.';
COMMENT ON COLUMN radar.schema_migrations.version IS
    'Migration file name, applied in lexical order.';
COMMENT ON COLUMN radar.schema_migrations.applied_at IS
    'When the migration ran.';

-- indexes -----------------------------------------------------------
COMMENT ON INDEX radar.findings_upload_category IS
    'Serves reading an upload''s findings, grouped by category.';
COMMENT ON INDEX radar.briefs_upload_category IS
    'Serves assembling an assessment from its briefs.';
