-- Document the `radar` schema in the database, so anyone reading
-- the state with psql learns what a column means without a
-- document beside it. COMMENT ON is idempotent: re-running this
-- migration replaces the text rather than failing.

COMMENT ON SCHEMA radar IS
    'State for pgEdge Radar Analyst: uploaded radar archives and '
    'the assessments derived from them. Never holds anything about '
    'the PostgreSQL server an archive was collected from.';

-- uploads -----------------------------------------------------------
COMMENT ON TABLE radar.uploads IS
    'One uploaded radar archive. The bytes live in the blob store; '
    'this row holds where they are and what the archive says about '
    'itself.';
COMMENT ON COLUMN radar.uploads.id IS
    'Upload identifier, generated by the service and used in every '
    'API path for this archive.';
COMMENT ON COLUMN radar.uploads.filename IS
    'Name the archive was uploaded under, as given by the client.';
COMMENT ON COLUMN radar.uploads.storage_url IS
    'Opaque blob-store address, for example file:// for the local '
    'filesystem store. The schema does not depend on the scheme.';
COMMENT ON COLUMN radar.uploads.size_bytes IS
    'Size of the stored archive in bytes, counted while streaming '
    'it in.';
COMMENT ON COLUMN radar.uploads.sha256 IS
    'Hex sha256 of the stored archive, computed in the same '
    'streaming pass as size_bytes.';
COMMENT ON COLUMN radar.uploads.hostname IS
    'Host the archive was collected from, as reported inside the '
    'archive. Null when the archive does not say.';
COMMENT ON COLUMN radar.uploads.archive_timestamp IS
    'When radar collected the archive, as reported inside it. Null '
    'when the archive does not say.';
COMMENT ON COLUMN radar.uploads.created_at IS
    'When the upload was accepted by the service.';
COMMENT ON COLUMN radar.uploads.archive_files IS
    'Inventory of every entry in the archive, as a JSON array of '
    '{path, kind, dbname, size}. Entries no parser claims are '
    'stored with kind = null, which is how a new radar collector '
    'shows up rather than disappearing silently.';

-- jobs --------------------------------------------------------------
COMMENT ON TABLE radar.jobs IS
    'One assessment run over one upload. Deleted with its upload.';
COMMENT ON COLUMN radar.jobs.id IS
    'Job identifier, used in the job and progress-stream paths.';
COMMENT ON COLUMN radar.jobs.upload_id IS
    'Archive this job assessed.';
COMMENT ON COLUMN radar.jobs.state IS
    'queued, running, done, or failed.';
COMMENT ON COLUMN radar.jobs.phase IS
    'Pipeline stage currently running, for the progress stream. '
    'Null before the job starts and after it ends.';
COMMENT ON COLUMN radar.jobs.started_at IS
    'When the job began, or null while it is still queued.';
COMMENT ON COLUMN radar.jobs.finished_at IS
    'When the job reached done or failed, or null while running.';
COMMENT ON COLUMN radar.jobs.error IS
    'Why the job failed. Null on success.';
COMMENT ON COLUMN radar.jobs.ai_provider IS
    'Provider that was configured for this run, recorded so a '
    'brief can be read in the light of what wrote it.';

-- snapshots ---------------------------------------------------------
COMMENT ON TABLE radar.snapshots IS
    'Parsed host and PostgreSQL context for one upload, plus the '
    'coverage canary listing archive paths no parser claimed.';
COMMENT ON COLUMN radar.snapshots.upload_id IS
    'Archive this snapshot was parsed from.';
COMMENT ON COLUMN radar.snapshots.data IS
    'The snapshot itself: host facts, PostgreSQL settings, '
    'per-database summaries, and unknown_entries.';

-- findings ----------------------------------------------------------
COMMENT ON TABLE radar.findings IS
    'Deterministic results. Every row was produced by a rule in '
    'rules/, never by a language model, so the same archive always '
    'yields the same findings.';
COMMENT ON COLUMN radar.findings.id IS
    'Finding identifier.';
COMMENT ON COLUMN radar.findings.upload_id IS
    'Archive this finding was derived from.';
COMMENT ON COLUMN radar.findings.rule_id IS
    'Rule that fired, matching the name in rules/.';
COMMENT ON COLUMN radar.findings.category IS
    'Diagnostic category this finding is reported under.';
COMMENT ON COLUMN radar.findings.severity IS
    'How bad it is. Sets the floor for the category verdict, which '
    'is why a verdict survives a provider outage.';
COMMENT ON COLUMN radar.findings.title IS
    'One-line statement of what was found.';
COMMENT ON COLUMN radar.findings.detail IS
    'Longer explanation, including what to do about it.';
COMMENT ON COLUMN radar.findings.evidence IS
    'The values the rule fired on, so the finding can be checked '
    'against the archive.';

-- briefs ------------------------------------------------------------
COMMENT ON TABLE radar.briefs IS
    'Per-category narrative written by the configured provider. '
    'The only part of an assessment that can be missing: findings '
    'and verdicts do not depend on a provider answering.';
COMMENT ON COLUMN radar.briefs.id IS
    'Brief identifier.';
COMMENT ON COLUMN radar.briefs.upload_id IS
    'Archive this brief describes.';
COMMENT ON COLUMN radar.briefs.category IS
    'Diagnostic category, or a per-database key for a '
    'database-level brief.';
COMMENT ON COLUMN radar.briefs.provider IS
    'Provider that produced this brief.';
COMMENT ON COLUMN radar.briefs.model IS
    'Model that produced this brief.';
COMMENT ON COLUMN radar.briefs.verdict IS
    'HEALTHY, WARNING, or CRITICAL, never below the floor set by '
    'this category''s worst finding. UNKNOWN means the archive '
    'carried no data for the category.';
COMMENT ON COLUMN radar.briefs.markdown IS
    'The brief itself. Carries a short "unavailable" note when the '
    'provider could not be reached.';
COMMENT ON COLUMN radar.briefs.prompt_tokens IS
    'Prompt tokens billed for this brief, when the provider '
    'reports them.';
COMMENT ON COLUMN radar.briefs.completion_tokens IS
    'Completion tokens billed for this brief, when the provider '
    'reports them.';
COMMENT ON COLUMN radar.briefs.created_at IS
    'When the brief was written.';

-- schema_migrations -------------------------------------------------
COMMENT ON TABLE radar.schema_migrations IS
    'Which migration files have been applied. Written by the '
    'service at startup.';
COMMENT ON COLUMN radar.schema_migrations.version IS
    'Migration file name, applied in lexical order.';
COMMENT ON COLUMN radar.schema_migrations.applied_at IS
    'When the migration ran.';

-- indexes -----------------------------------------------------------
COMMENT ON INDEX radar.findings_upload_severity IS
    'Serves the roll-up, which needs the worst severity per upload.';
COMMENT ON INDEX radar.findings_upload_category IS
    'Serves reading one category''s findings for its brief.';
COMMENT ON INDEX radar.briefs_upload_category IS
    'Serves assembling an assessment from its briefs.';
